// Tor client for the desktop shell (PLAN-TOR D7). One child process, spawned
// LAZILY the first time a `.onion` host is actually wanted — a person who never
// signs in to an onion server never pays for it.
//
// No ControlPort and no cookie auth: both facts we need (the SOCKS port tor
// picked, and "bootstrapped") arrive on a stdout stream we have to read anyway
// to keep the pipe from filling. One regex beats a control-protocol client.
//
// The binary itself: bundled `tor.exe` on packaged Windows (PR 3 ships it),
// otherwise a system `tor` on PATH (`brew install tor` / `apt install tor`),
// otherwise `OMB_TOR_BIN` for a dev machine. If none of the three is there, an
// onion address is simply unavailable and the sign-in screen says so — never a
// silent direct connection, which would put the address in a DNS query.
import { spawn } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { delimiter, join } from "node:path";
import { connect as tlsConnect } from "node:tls";

import { socksConnect } from "./socks5.mjs";

/** No tor on this computer — the one code the sign-in screen turns into a
 * sentence. */
export const TOR_UNAVAILABLE = "MULTIBOT_TOR_UNAVAILABLE";

const BOOTSTRAP_BUDGET_MS = 90_000;

/** Tor's own wording has shifted between releases ("Opened Socks listener on",
 * "Opened Socks listener connection (ready) on"), so we anchor on the two ends
 * of the line and not on what sits between them. */
const SOCKS_LINE = /Opened Socks listener\b[^\n]*?\bon 127\.0\.0\.1:(\d{1,5})/;

/** One line of tor's log → what it tells us, or `null` for the other 99%. */
export function parseTorLine(line) {
  const socks = SOCKS_LINE.exec(line);
  if (socks) return { socksPort: Number(socks[1]) };
  if (/Bootstrapped 100%/.test(line)) return { bootstrapped: true };
  return null;
}

/** A torrc value that survives a Windows path: tor reads the rest of the line
 * verbatim unless it is quoted, and inside quotes a backslash is an escape —
 * so `C:\Users\…` MUST NOT be quoted unless its backslashes are doubled. */
function torrcValue(text) {
  const value = String(text);
  return /\s/.test(value) ? `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"` : value;
}

/** The client torrc from PLAN-TOR, rewritten on every start. `ClientOnly 1` is
 * the line that matters: this process must never become a relay.
 *
 * No `GeoIPFile`/`GeoIPv6File`: PR 3 ships a static `tor.exe` and nothing else,
 * so pointing at geoip files that are not there would only make tor warn. They
 * feed bridge country selection and relay statistics — a plain client needs
 * neither. */
export function torrcText({ dataDir }) {
  const lines = [
    "# generated by electron/tor.mjs — edits are overwritten",
    `DataDirectory ${torrcValue(dataDir)}`,
    "SocksPort auto",
    "ClientOnly 1",
    "Log notice stdout",
    "AvoidDiskWrites 1",
  ];
  return lines.join("\n") + "\n";
}

function findOnPath(name, env, exists) {
  for (const dir of String(env.PATH ?? env.Path ?? "").split(delimiter)) {
    if (!dir) continue;
    const full = join(dir, name);
    if (exists(full)) return full;
  }
  return null;
}

/**
 * Where the tor binary is, or `null` when this computer has none. Pure apart
 * from the injected `exists`, so the missing-binary path is testable without
 * uninstalling anything.
 */
export function resolveTorBinary({ resourcesPath = null, platform = process.platform, env = process.env, exists = existsSync } = {}) {
  // The whole feature has an off switch, and it is the same one the server uses.
  if (env.OMB_TOR === "0") return null;
  if (platform === "win32" && resourcesPath) {
    const bundled = join(resourcesPath, "tor", "tor.exe");
    if (exists(bundled)) return bundled;
  }
  const onPath = findOnPath(platform === "win32" ? "tor.exe" : "tor", env, exists);
  if (onPath) return onPath;
  const dev = env.OMB_TOR_BIN;
  return dev && exists(dev) ? dev : null;
}

let settings = { dataDir: null, resourcesPath: null };
let starting = null;
let child = null;

/** Told once, at app start: where tor may keep its state and where a bundled
 * copy would live. Kept out of `startTor` so the connector below can be handed
 * to node's HTTP client as a bare function. */
export function configureTor(next) {
  settings = { ...settings, ...next };
}

function spawnTor({ dataDir, resourcesPath, budgetMs }) {
  return new Promise((resolveWith, rejectWith) => {
    const bin = resolveTorBinary({ resourcesPath });
    if (!bin || !dataDir) {
      rejectWith(Object.assign(new Error("tor is not available on this computer"), { code: TOR_UNAVAILABLE }));
      return;
    }
    mkdirSync(dataDir, { recursive: true });
    const torrc = join(dataDir, "torrc");
    writeFileSync(torrc, torrcText({ dataDir }));

    const proc = spawn(bin, ["-f", torrc], { stdio: ["ignore", "pipe", "pipe"], windowsHide: true });
    child = proc;
    let socksPort = 0;
    let bootstrapped = false;
    let tail = "";
    let lastError = "";
    let settled = false;

    const fail = (err) => {
      if (settled) return;
      settled = true;
      clearTimeout(budget);
      try {
        proc.kill();
      } catch {
        /* already gone */
      }
      if (child === proc) child = null;
      rejectWith(err);
    };
    const budget = setTimeout(() => fail(new Error(`tor did not bootstrap in ${Math.round(budgetMs / 1000)} s`)), budgetMs);

    const onLine = (line) => {
      const fact = parseTorLine(line);
      if (fact?.socksPort) socksPort = fact.socksPort;
      if (fact?.bootstrapped) bootstrapped = true;
      if (settled || !socksPort || !bootstrapped) return;
      settled = true;
      clearTimeout(budget);
      proc.stdout.off("data", onData);
      // Nobody reads this stream any more, but SOMETHING has to: an unread pipe
      // fills and then tor blocks on its own logging. `resume()` without a
      // listener is the cheapest drain there is.
      proc.stdout.resume();
      resolveWith({ socksPort, child: proc });
    };
    const onData = (chunk) => {
      tail += String(chunk);
      const lines = tail.split("\n");
      tail = lines.pop() ?? "";
      for (const line of lines) onLine(line);
    };

    proc.stdout.on("data", onData);
    proc.stderr.on("data", (chunk) => {
      lastError = String(chunk).slice(0, 200);
    });
    proc.on("error", (err) => fail(err.code === "ENOENT" ? Object.assign(err, { code: TOR_UNAVAILABLE }) : err));
    proc.on("exit", (code) => {
      const ours = child === proc;
      if (ours) child = null;
      if (settled) {
        // Tor died after it was up. Forget the resolved promise, or every later
        // onion request would dial a SOCKS port that is not there any more.
        if (ours) starting = null;
        return;
      }
      fail(new Error(`tor exited with ${code}${lastError ? `: ${lastError.trim()}` : ""}`));
    });
  });
}

/**
 * Starts tor once and hands every later caller the same promise. A FAILED start
 * clears it, so a person who installs tor and tries again is not stuck with the
 * first answer for the life of the process.
 *
 * @returns {Promise<{ socksPort: number }>}
 */
export function startTor(options = {}) {
  if (options.dataDir || options.resourcesPath) configureTor(options);
  if (starting) return starting;
  starting = spawnTor({ ...settings, budgetMs: options.budgetMs ?? BOOTSTRAP_BUDGET_MS }).catch((err) => {
    starting = null;
    throw err;
  });
  return starting;
}

/** Kills the child and forgets it. Idempotent: quitting calls it, and so does
 * closing the last window. */
export function stopTor() {
  starting = null;
  const proc = child;
  child = null;
  try {
    proc?.kill();
  } catch {
    /* already gone */
  }
}

/**
 * `createConnection` for node's http(s) client, reaching a `.onion` through our
 * own tor. Given to a request directly (no agent) or installed on an Agent —
 * both call it with the same `(options, callback)` contract.
 *
 * TLS is finished HERE because the request has no agent left to do it. Nothing
 * about the pin changes: `electron/tls-pin.mjs` compares `fingerprint256` on
 * 'secureConnect', which fires on this socket exactly as on a dialled one, and
 * `servername` is not set — the pin never looks at a SAN.
 */
export function onionCreateConnection(options, callback) {
  const host = options.host ?? options.hostname;
  const port = Number(options.port) || (options.protocol === "http:" ? 80 : 443);
  startTor()
    .then(({ socksPort }) => socksConnect({ socksPort, host, port }))
    .then((socket) => {
      if (options.protocol === "http:") {
        callback(null, socket);
        // `socksConnect` oddaje gniazdo ZAPAUZOWANE, a klient HTTP go nie
        // wznawia — nigdy nie dostaje takiego z `net.connect`. Wznowienie idzie
        // przez `nextTick`, bo dokładnie wtedy podpina swój parser
        // (`onSocketNT`); zrobione wcześniej zgubiłoby to, co już jest w buforze.
        // Droga HTTPS tego nie potrzebuje: `tls.connect` przejmuje uchwyt.
        process.nextTick(() => socket.resume());
        return;
      }
      // `servername` zdejmujemy (D3): przypięcie porównuje `fingerprint256` i
      // nigdy nie zagląda do SAN, a agent HTTPS dokłada je sam z nagłówka Host.
      const { servername: _sni, ...rest } = options;
      let secure;
      try {
        secure = tlsConnect({ ...rest, socket });
      } catch (err) {
        // Tunel jest NASZ do chwili, w której ktoś go od nas odbierze. Gdyby
        // TLS wywrócił się tutaj, nikt inny by go już nie zamknął.
        socket.destroy();
        callback(err);
        return;
      }
      secure.on("error", () => socket.destroy());
      callback(null, secure);
    })
    .catch(callback);
  // Undefined on purpose: node waits for the callback when nothing is returned.
  return undefined;
}
