// multibot (0.5.0): the address rung that works from every network — a v3 onion
// service, published by a `tor` this harness owns.
//
// Why the harness owns the child instead of a second runit service next to
// `mb-relay`: `ssh -R` needs nothing back from the server, tor does. We must
// know the SOCKS port to self-probe our own onion, and read `hs/hostname` the
// moment it appears. Owning the process gives both for free, and — decisive —
// the packaged Windows desktop also hosts a server and has no runit or systemd,
// so a service-based design would need a second supervisor. One file covers
// Termux, Linux, Windows and the packaged app. The lifetime coupling is the
// correct one: an onion whose harness is down is a published dead address.
//
// `OMB_TOR=0` turns the whole thing off. No tor binary anywhere is not an
// error either: one line in the log and the address ladder simply has one rung
// fewer.
import { spawn, type ChildProcess } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createServer, type Server as NetServer } from "node:net";
import type { Server as HttpServer } from "node:http";
import type { Server as HttpsServer } from "node:https";
import { delimiter, join } from "node:path";

import { isLoopbackAddress } from "./identity.ts";
import { isOnionHost } from "./net-address.ts";

/** The onion's own ingress. It exists so Tor clients do NOT share a socket with
 * loopback callers: `identityRateLimited` trusts `x-forwarded-for` from a
 * loopback peer (that is how a reverse proxy works), and every onion client IS
 * a loopback peer. Without a port of its own, an onion client could pick its
 * own rate-limit bucket and buy unlimited scrypt guesses at the server
 * password. */
export const TOR_INGRESS_PORT = 8798;
/** The port people type after the `.onion` name. Same as the direct one, so one
 * address shape is documented everywhere. */
export const ONION_PORT = 8799;
/** ponytail: one bucket for every Tor client — hiding the client IP is the
 * point of an onion, so a single global limit is the only honest one. */
export const TOR_BUCKET = "tor";
/** Tor publishes `hs/hostname` a second or two after it starts; a first ever
 * run also has to generate the key. Two minutes is generous and finite. */
const HOSTNAME_WAIT_MS = 120_000;
const RESTART_MIN_MS = 5_000;
const RESTART_MAX_MS = 60_000;

// ── pure pieces ──────────────────────────────────────────────────────

/** torrc takes C-style escapes inside a quoted value, so a data directory with
 * a space, a backslash or a quote in it survives verbatim instead of being
 * re-read as two options. A newline cannot be expressed at all — a path holding
 * one would smuggle whole config lines in, so it is refused outright. */
export function torPath(value: string): string {
  if (/[\r\n]/.test(value)) throw new Error(`tor: refusing a data directory with a newline in its path: ${JSON.stringify(value)}`);
  return `"${value.replace(/([\\"])/g, "\\$1")}"`;
}

/** Rewritten on every start: the harness owns this file, and a stale option
 * from an older version is a support call nobody can reproduce. */
export function torrcText(torDir: string, ingressPort = TOR_INGRESS_PORT, onionPort = ONION_PORT): string {
  return [
    "# generated by server/tor.ts — edits are overwritten on every start",
    `DataDirectory ${torPath(torDir)}`,
    // `auto` picks a free port and announces it on stdout; a fixed one would
    // collide with a system tor or a second harness on the same box.
    "SocksPort auto",
    `HiddenServiceDir ${torPath(join(torDir, "hs"))}`,
    "HiddenServiceVersion 3",
    `HiddenServicePort ${onionPort} 127.0.0.1:${ingressPort}`,
    "Log notice stdout",
    // A phone's flash is the thing that wears out, and none of this state is
    // worth a write amplification factor.
    "AvoidDiskWrites 1",
    "SafeLogging 1",
    "",
  ].join("\n");
}

/** `Opened Socks listener on 127.0.0.1:39471` (tor ≤ 0.4.5) and
 * `Opened Socks listener connection (ready) on 127.0.0.1:39471` (0.4.6+). */
export function parseSocksPort(line: string): number | null {
  const match = /Opened Socks listener (?:connection \(ready\) )?on (?:127\.0\.0\.1|\[::1\]|::1):(\d{1,5})/i.exec(line);
  const port = match ? Number(match[1]) : Number.NaN;
  return Number.isInteger(port) && port > 0 && port < 65_536 ? port : null;
}

/** `Bootstrapped 100% (done): Done` → 100. */
export function parseBootstrap(line: string): number | null {
  const match = /Bootstrapped (\d{1,3})%/i.exec(line);
  const percent = match ? Number(match[1]) : Number.NaN;
  return Number.isInteger(percent) && percent >= 0 && percent <= 100 ? percent : null;
}

/**
 * Which rate-limit bucket a request counts against.
 *
 * Over the Tor ingress the answer is the literal `"tor"` and `x-forwarded-for`
 * is not even read: every onion client arrives from 127.0.0.1, so honouring the
 * header there would let a client name its own bucket. Everywhere else the old
 * rule stands — the first forwarded hop, but ONLY when the socket peer really
 * is loopback, i.e. there is a reverse proxy in front.
 */
export function rateLimitAddress(
  socket: { localPort?: number | undefined; remoteAddress?: string | undefined },
  forwardedFor: string | string[] | undefined,
  ingressPort = TOR_INGRESS_PORT,
): string {
  if (socket.localPort === ingressPort) return TOR_BUCKET;
  const peer = socket.remoteAddress ?? "unknown";
  const forwarded = String(forwardedFor ?? "").split(",")[0].trim();
  return (isLoopbackAddress(socket.remoteAddress) && forwarded) || peer;
}

/** `OMB_TOR=0|off|false|no` — the same spelling `OMB_TLS` accepts. */
export function torEnabled(env: NodeJS.ProcessEnv = process.env): boolean {
  return !/^(0|off|false|no)$/i.test(env.OMB_TOR?.trim() ?? "");
}

/**
 * Where the `tor` executable is, in the order the deployments actually need:
 * an explicit override, then a system tor (`pkg install tor` on Termux,
 * `apt install tor` on Linux, `brew install tor` on mac), then — Windows only —
 * the copy the packaged desktop ships beside its resources.
 *
 * Returns null rather than throwing: no tor is a missing rung, not a failure.
 */
export function findTorBinary(env: NodeJS.ProcessEnv = process.env, platform = process.platform): string | null {
  const explicit = env.OMB_TOR_BIN?.trim();
  if (explicit) {
    if (existsSync(explicit)) return explicit;
    console.warn(`[multibot] OMB_TOR_BIN=${explicit} does not exist — looking for tor on PATH instead`);
  }
  const name = platform === "win32" ? "tor.exe" : "tor";
  for (const dir of (env.PATH ?? "").split(delimiter)) {
    if (!dir) continue;
    const candidate = join(dir.replace(/^"|"$/g, ""), name);
    if (existsSync(candidate)) return candidate;
  }
  // PR 3 puts the Expert-Bundle tor.exe here (`win.extraResources`); until then
  // this simply never matches and the desktop has no onion. `resourcesPath` is
  // Electron's, so it is absent in every other host — hence the guard, not a
  // type assertion that would lie about it always being there.
  const resources = (process as NodeJS.Process & { resourcesPath?: string }).resourcesPath;
  const packaged = platform === "win32" && resources ? join(resources, "tor", "tor.exe") : null;
  return packaged && existsSync(packaged) ? packaged : null;
}

/** `findTorBinary` with the answer remembered: the boot asks twice (once to
 * decide whether the built UI has to be served, once to start tor) and a
 * warning about a bad `OMB_TOR_BIN` is worth exactly one line. */
let cachedBinary: string | null | undefined;
export function torBinary(): string | null {
  if (cachedBinary === undefined) cachedBinary = findTorBinary();
  return cachedBinary;
}

// ── the ingress ──────────────────────────────────────────────────────

/**
 * The onion's own door into the harness.
 *
 * The harness cannot `listen()` twice on one `Server` object — it is already
 * wrapped by the webhook listener, `mountVncUpgrade`, `mountEventsWs` and
 * `mountAuth`. So a bare TCP server takes the connection and hands it to the
 * very same `Server` by emitting `"connection"`, which `tls.Server` accepts
 * from outside just as it does from its own handle. `req.socket.localPort` then
 * reads 8798, which is how everything downstream knows the request came in over
 * Tor.
 */
export function mountTorIngress(
  server: HttpServer | HttpsServer,
  port = TOR_INGRESS_PORT,
  host = "127.0.0.1",
): NetServer {
  const ingress = createServer((socket) => server.emit("connection", socket));
  ingress.on("error", (error) => console.warn("[multibot] tor ingress failed:", error instanceof Error ? error.message : error));
  ingress.listen(port, host);
  return ingress;
}

// ── the supervisor ───────────────────────────────────────────────────

export type Tor = {
  /** The `.onion` host, or null until tor has published it. */
  onionHost(): string | null;
  /** The SOCKS port tor picked, for our own self-probe. */
  socksPort(): number | null;
  stop(): void;
};

export type TorOptions = {
  dataDir: string;
  server: HttpServer | HttpsServer;
  onionPort?: number;
  ingressPort?: number;
  /** Fired once, when the hostname first appears — the cue to rescan the
   * address ladder instead of waiting out the ten-minute tick. */
  onReady?(host: string): void;
};

export function startTor(options: TorOptions): Tor | null {
  if (!torEnabled()) {
    console.log("[multibot] OMB_TOR=0 — no onion address on this server");
    return null;
  }
  const binary = torBinary();
  if (!binary) {
    console.log("[multibot] no `tor` found (PATH, OMB_TOR_BIN) — no onion address. Termux: `pkg install tor`; Debian/Ubuntu: `apt install tor`; macOS: `brew install tor`.");
    return null;
  }

  const torDir = join(options.dataDir, "tor");
  const hsDir = join(torDir, "hs");
  const torrcFile = join(torDir, "torrc");
  const ingressPort = options.ingressPort ?? TOR_INGRESS_PORT;
  try {
    // 0700 on both, or tor refuses to touch the hidden-service directory at
    // all — the private key that IS the onion address lives in it.
    mkdirSync(torDir, { recursive: true, mode: 0o700 });
    mkdirSync(hsDir, { recursive: true, mode: 0o700 });
    writeFileSync(torrcFile, torrcText(torDir, ingressPort, options.onionPort ?? ONION_PORT), { mode: 0o600 });
  } catch (error) {
    console.warn("[multibot] could not prepare the tor directory — no onion address:", error instanceof Error ? error.message : error);
    return null;
  }

  const ingress = mountTorIngress(options.server, ingressPort);
  const hostnameFile = join(hsDir, "hostname");
  let onion: string | null = null;
  let socks: number | null = null;
  let child: ChildProcess | null = null;
  let stopped = false;
  let backoff = RESTART_MIN_MS;
  let restartTimer: NodeJS.Timeout | null = null;

  const readOnion = (): string | null => {
    if (onion) return onion;
    try {
      const value = readFileSync(hostnameFile, "utf8").trim().toLowerCase();
      // The file is ours, but it is still a file: a truncated or half-written
      // read must not become an address we publish.
      if (isOnionHost(value)) onion = value;
    } catch {
      /* not published yet */
    }
    return onion;
  };

  const note = (line: string): void => {
    const port = parseSocksPort(line);
    if (port) {
      socks = port;
      console.log(`[multibot] tor socks port ${port}`);
    }
    if (parseBootstrap(line) === 100) {
      // A tor that reached 100% is healthy; whatever the previous crash loop
      // had wound the delay up to is no longer relevant.
      backoff = RESTART_MIN_MS;
      console.log("[multibot] tor bootstrapped");
    }
  };

  const run = (): void => {
    if (stopped) return;
    // stdout carries `Log notice stdout`; stderr carries startup errors (a bad
    // torrc, a locked data directory) and is the only place they appear.
    child = spawn(binary, ["-f", torrcFile], { stdio: ["ignore", "pipe", "pipe"], windowsHide: true });
    socks = null;
    let tail = "";
    const onChunk = (chunk: Buffer): void => {
      tail += chunk.toString("utf8");
      const lines = tail.split(/\r?\n/);
      tail = lines.pop() ?? "";
      // A peer that never sends a newline must not grow this forever.
      if (tail.length > 4096) tail = "";
      for (const line of lines) note(line);
    };
    child.stdout?.on("data", onChunk);
    child.stderr?.on("data", (chunk: Buffer) => {
      onChunk(chunk);
      console.warn(`[multibot] tor: ${chunk.toString("utf8").trim().slice(0, 400)}`);
    });
    child.on("error", (error) => console.warn("[multibot] tor failed to start:", error.message));
    child.on("exit", (code, signal) => {
      child = null;
      if (stopped) return;
      console.warn(`[multibot] tor exited (${signal ?? code}) — restarting in ${Math.round(backoff / 1000)} s`);
      restartTimer = setTimeout(run, backoff);
      restartTimer.unref?.();
      backoff = Math.min(backoff * 2, RESTART_MAX_MS);
    });
  };
  run();

  // One poll a second until the hostname shows up, then never again: the file
  // is written once and the address does not change.
  const deadline = Date.now() + HOSTNAME_WAIT_MS;
  const poll = setInterval(() => {
    const host = readOnion();
    if (host) {
      clearInterval(poll);
      console.log(`[multibot] onion address https://${host}:${options.onionPort ?? ONION_PORT}`);
      options.onReady?.(host);
    } else if (Date.now() > deadline) {
      clearInterval(poll);
      console.warn(`[multibot] tor did not publish ${hostnameFile} within 2 min — no onion address for now`);
    }
  }, 1_000);
  poll.unref?.();

  const stop = (): void => {
    if (stopped) return;
    stopped = true;
    clearInterval(poll);
    if (restartTimer) clearTimeout(restartTimer);
    // tor spawns no children of its own, so one signal is the whole tree. It is
    // also registered on `exit`, because a tor left running holds the data
    // directory lock and the NEXT harness would then never get its onion back.
    try {
      child?.kill();
    } catch {
      /* already gone */
    }
    child = null;
    ingress.close();
  };
  process.once("exit", stop);

  return { onionHost: readOnion, socksPort: () => socks, stop };
}
